version: "3"
services:
    redis:
      image: redis:3.2
      networks:
        - databases
      restart: unless-stopped
      ports:
        - "6379:6379"

    mongo:
      image: mongo:2.4
      networks:
        - databases
      restart: unless-stopped
      ports:
        - "27017:27017"

    postgres:
      image: postgres:9.6.2
      networks:
        - databases
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: ''
      ports:
        - "5432:5432"

networks:
  databases:
    driver: bridge
